version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datafile
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elasticnetwork
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticnetwork
  case:
    image: ${DOCKER_REGISTRY-}aqvatechcase
    ports:
      - 5000:8080
    depends_on:
    - elasticsearch
    networks:
    - elasticnetwork
    build:
      context: .
      dockerfile: AqvaTechCase/Dockerfile 
networks:
  elasticnetwork:
    driver: bridge

volumes:
  elasticsearch-data:
      